[package]
name = "example"
version = "0.6.0"
edition = "2021"

[dependencies]
winit = "0.29.10"
wgpu = "0.19.0"
futures = "0.3"
bytemuck = { version = "1.13", features = [ "derive" ] }
encase = { version = "0.7.0", features = ["glam"] }
glam = { version = "0.25.0", features = ["bytemuck"] }
memoffset = "0.9.0"

[build-dependencies]
wgsl_to_wgpu = { path = "../wgsl_to_wgpu" }
